---
display:
  display_rate: 0.55 # in seconds

#SimWorld args:
sim_world:
  world: "hex"
  size: 6

actor:
  episodes: 20
  num_checkpoints: 6
  train_ex_size: 320
  competition_games: 400
  file_structure: "anets/local/hex/6x6/"
  epsilon: 0.15
  epsilon_decay: 0.96
  epsilon_min: 0.1

mcts:
  search_duration: 6.0
  bias: 0.34
  c: 0.11
  min_h_confidence: 4
  max_h_confidence: 15
  amaf_conf_scalar: 1
  max_rollouts: 50000
  search_games: 600


anet:
  lr: 0.000275
  optimizer: "adam"
  loss: "categorical_crossentropy"
  model_file: "anets/local/hex/6x6/temp.h5"
  activation: "selu"
  cnn_filters: # depth, filter_size, dropout (on layer output!!), padding
    - [148, 3, 0.0, "valid"]
    - [148, 3, 0.0, "same"]
    - [148, 3, 0.0, "same"]
    - [148, 3, 0.0, "same"]
    - [148, 3, 0.05, "same"]
    - [12, 1, 0.01, "same"]
  dense_layers: # depth, dropout
    - [64, 0.0]
  #  - [512, 0.2]
  #  - [256, 0.2]
  batch_size: 64
  allow_cuda: False