---
#SimWorld args:
episodes: 100
sim_world: 
  world: "peg_solitaire"
  type: "diamond"
  size: 4
  #Display:
  display:
    train_display: false
    display_rate: 0.6 # in seconds
  
#Critic args:
critic:
  type: "neural_net"
  size:
    - 15
    - 20
    - 30
    - 5
    - 1
  lr: 0.5
  eligibility_decay: 0.75
  discount_factor: 0.9
  
#Actor args:
actor:
  lr: 2.0
  eligibility_decay: 0.75
  discount_factor: 0.9
  greedy_epsilon: 0.5
  epsilon_decay: 0.9 # set to 1 for no decay
