---
#SimWorld args:
sim_world: 
  world: "peg_solitaire"
  type: "triangle"
  size: 4
  open_cells: 2
  episodes: 10
  
#Critic args:
critic:
  type: "neural_net"
  size:
    - 15
    - 20
    - 30
    - 5
    - 1
  lr: 0.001
  eligibility_decay: 0.05
  discount_factor: 0.9
  
#Actor args:
actor:
  lr: 0.1
  eligibility_decay: 0.05
  discount_factor: 0.9
  greedy_epsilon: 0.5
  epsilon_decay: 0.9 # set to 1 for no decay
  
#Display:
display:
  train_display: false
  display_rate: 1000 # in milliseconds
  
