---
episodes: 500
display_episodes:
    - 600
display_greedy: True
#SimWorld args:
sim_world:
  world: "peg_solitaire"
  type: "diamond"
  size: 4
  #Display:
  display_rate: 0.78 # in seconds


#Critic args:
critic:
  type: "neural_net"
  hidden_layers:
    - 20
    - 30
    - 10
  lr: 0.00003
  eligibility_decay: 0.6
  discount_factor: 0.9

#Actor args:
actor:
  lr: 0.7
  eligibility_decay: 0.75
  discount_factor: 0.9
  greedy_epsilon: 0.8
  epsilon_decay: 0.985 # set to 1 for no decay
