---
episodes: 600
display_episodes:
    - 99
#SimWorld args:
sim_world:
  world: "peg_solitaire"
  type: "diamond"
  size: 4
  #Display:
  display_rate: 0.08 # in seconds


#Critic args:
critic:
  type: "neural_net"
  hidden_layers:
    - 20
    - 20
    - 5
  lr: 0.00001
  eligibility_decay: 0.75
  discount_factor: 0.9

#Actor args:
actor:
  lr: 1.75
  eligibility_decay: 0.75
  discount_factor: 0.9
  greedy_epsilon: 0.75
  epsilon_decay: 0.985 # set to 1 for no decay
