episodes: 600
display_episodes:
    - 600
display_greedy: True
#SimWorld args:
sim_world:
  world: "peg_solitaire"
  type: "triangle"
  size: 5
  #Display:
  display_rate: 0.18 # in seconds


#Critic args:
critic:
  type: "neural_net"
  hidden_layers:
    - 20
    - 30
    - 10
  lr: 0.00004
  eligibility_decay: 0.55
  discount_factor: 0.9

#Actor args:
actor:
  lr: 0.675
  eligibility_decay: 0.765
  discount_factor: 0.9
  greedy_epsilon: 0.8
  epsilon_decay: 0.985 # set to 1 for no decay