---
episodes: 500
display_episodes:
    - 500
display_greedy: True
#SimWorld args:
sim_world:
  world: "peg_solitaire"
  type: "triangle"
  size: 5
  #Display:
  display_rate: 0.51 # in seconds


#Critic args:
critic:
  type: "table"
  lr: 0.6
  eligibility_decay: 0.7
  discount_factor: 0.9

#Actor args:
actor:
  lr: 0.9
  eligibility_decay: 0.75
  discount_factor: 0.9
  greedy_epsilon: 0.6
  epsilon_decay: 0.95 # set to 1 for no decay

