---
episodes: 100
display_episodes:
    - 100
display_greedy: True
#SimWorld args:
sim_world:
  world: "peg_solitaire"
  type: "diamond"
  size: 4
  #Display:
  display_rate: 0.57 # in seconds


#Critic args:
critic:
  type: "table"
  lr: 0.75
  eligibility_decay: 0.75
  discount_factor: 0.9

#Actor args:
actor:
  lr: 3.0
  eligibility_decay: 0.75
  discount_factor: 0.9
  greedy_epsilon: 0.5
  epsilon_decay: 0.9 # set to 1 for no decay
