---
display:
  display_rate: 0.55 # in seconds

#SimWorld args:
sim_world:
  world: "hex"
  size: 4

actor:
   episodes: 1000
   num_checkpoints: 21
   epsilon: 0.8
   epsilon_decay: 0.985
   epsilon_min: 0.15

mcts:
  search_duration: 1.1
  bias: 0.215
  c: 0


anet:
  lr: 0.0002
  optimizer: "adam"
  loss: "categorical_crossentropy"
  file_structure: "anet/hex/conv2/"
  model_file: "anet/hex/conv/checkpoint_884.h5"
  activation: "relu"
  l1_filters: 64
  l2_filters: 96
  l3_filters: 96
  fc1_width: 512
  fc2_width: 256
  dropout: 0.2
  allow_cuda: False