---
display:
  display_rate: 0.55 # in seconds

#SimWorld args:
sim_world:
  world: "hex"
  size: 4

actor:
   episodes: 40
   num_checkpoints: 6
   epsilon: 0.4
   epsilon_decay: 0.985
   epsilon_min: 0.1

mcts:
  search_duration: 2.5
  bias: 0.3
  c: 0


anet:
  lr: 0.00025
  optimizer: "SGD"
  loss: "categorical_crossentropy"
  file_structure: "anet/hex2/"
  output_activation: "softmax"
  hidden_layers:
    - [40, "linear"]
    - [30, "linear"]
    - [25, "linear"]
