---
display:
  display_rate: 0.55 # in seconds

#SimWorld args:
sim_world:
  world: "hex"
  size: 4

actor:
   episodes: 40
   num_checkpoints: 4
   epsilon: 0.6
   epsilon_decay: 0.96
   epsilon_min: 0.1

mcts:
  search_duration: 1.0
  bias: 0.225
  c: 0


anet:
  lr: 0.0001
  optimizer: "adam"
  loss: "categorical_crossentropy"
  file_structure: "anet/hex/zero_c/"
  output_activation: "softmax"
  activation: "relu"
  l1_filters: 32
  l2_filters: 64
  l3_filters: 64
  dropout: 0.15