---
display:
  display_rate: 0.55 # in seconds

#SimWorld args:
sim_world:
  world: "hex"
  size: 5

actor:
  type: "tour" # standard
  episodes: 500
  num_checkpoints: 11
  train_ex_size: 256
  competition_games: 0
  file_structure: "anet/hex/conv3/"
  epsilon: 0.7
  epsilon_decay: 0.98
  epsilon_min: 0.1

mcts:
  search_duration: 1.0
  bias: 0.215
  c: 0
  min_h_confidence: 5
  max_h_confidence: 50
  amaf_conf_scalar: 2


anet:
  lr: 0.0003
  optimizer: "adam"
  loss: "categorical_crossentropy"
  model_file: "anet/hex/conv3/temp.h5"
  activation: "relu"
  l1_filters: 196
  l2_filters: 196
  l3_filters: 196
  fc1_width: 512
  fc2_width: 256
  dropout: 0.2
  batch_size: 32
  allow_cuda: False