---
display:
  display_rate: 0.55 # in seconds

#SimWorld args:
sim_world:
  world: "hex"
  size: 5

actor:
  type: "tour" # standard
  episodes: 200
  num_checkpoints: 11
  train_ex_size: 256
  competition_games: 0
  file_structure: "anets/local/hex/conv1/"
  epsilon: 0.7
  epsilon_decay: 0.98
  epsilon_min: 0.1

mcts:
  search_duration: 1.0
  bias: 0.215
  c: 0
  min_h_confidence: 5
  max_h_confidence: 50
  amaf_conf_scalar: 2


anet:
  lr: 0.0005
  optimizer: "adam"
  loss: "categorical_crossentropy"
  #model_file: "anets/best/hex/5x5/temp.h5"
  activation: "selu"
  cnn_filters: # depth, dropout, padding
    - [196, 0.0, "same"]
    - [196, 0.0, "same"]
    - [256, 0.1, "valid"]
  dense_layers: # depth, dropout
    - [512, 0.2]
    - [256, 0.2]
  batch_size: 32
  allow_cuda: False