---
display:
  display_rate: 0.55 # in seconds

#SimWorld args:
sim_world:
  world: "hex"
  size: 5

actor:
  episodes: 100
  num_checkpoints: 3
  train_ex_size: 256
  competition_games: 0
  file_structure: "anet/hex/conv2/"
  epsilon: 0.7
  epsilon_decay: 0.98
  epsilon_min: 0.1

mcts:
  search_duration: 1.0
  bias: 0.215
  c: 0


anet:
  lr: 0.0003
  optimizer: "adam"
  loss: "categorical_crossentropy"
  model_file: "anet/hex/conv2/temp.h5"
  activation: "relu"
  l1_filters: 64
  l2_filters: 128
  l3_filters: 196
  fc1_width: 512
  fc2_width: 256
  dropout: 0.2
  batch_size: 32
  allow_cuda: False