---
display:
  display_rate: 0.55 # in seconds

#SimWorld args:
sim_world:
  world: "hex"
  size: 5

actor:
  type: "tour" # standard
  episodes: 200
  num_checkpoints: 6
  train_ex_size: 6
  competition_games: 200
  file_structure: "anets/local/hex/b_0.4/"
  epsilon: 0.7
  epsilon_decay: 0.98
  epsilon_min: 0.1

mcts:
  search_duration: 1.25
  bias: 0.4
  c: 0
  min_h_confidence: 5
  max_h_confidence: 50
  amaf_conf_scalar: 2


anet:
  lr: 0.0003
  optimizer: "adam"
  loss: "categorical_crossentropy"
  model_file: "anets/local/hex/b_0.4/temp.h5"
  activation: "relu"
  cnn_filters: # depth, dropout, padding
    - [196, 0.1, "same"]
    - [196, 0.1, "same"]
    - [196, 0.1, "same"]
  dense_layers: # depth, dropout
    - [512, 0.2]
    - [256, 0.2]
  batch_size: 32
  allow_cuda: False