---
display:
  display_rate: 0.55 # in seconds

#SimWorld args:
sim_world:
  world: "hex"
  size: 4

actor:
   episodes: 200
   num_checkpoints: 11
   epsilon: 0.6
   epsilon_decay: 0.96
   epsilon_min: 0.1

mcts:
  search_duration: 1.0
  bias: 0.225
  c: 0


anet:
  lr: 0.00025
  optimizer: "adam"
  loss: "categorical_crossentropy"
  file_structure: "anet/hex/conv/"
  activation: "relu"
  l1_filters: 64
  l2_filters: 96
  l3_filters: 96
  fc1_width: 512
  fc2_width: 256
  dropout: 0.15
  allow_cuda: False