---
display:
  display_rate: 0.55 # in seconds

#SimWorld args:
sim_world:
  world: "hex"
  size: 5

actor:
  episodes: 20
  num_checkpoints: 6
  train_ex_size: 386
  competition_games: 600
  file_structure: "anets/local/hex/5x5_small_dense/"
  epsilon: 0.075
  epsilon_decay: 0.96
  epsilon_min: 0.075

mcts:
  search_duration: 3.0
  bias: 0.44
  c: 0.075
  min_h_confidence: 5
  max_h_confidence: 15
  amaf_conf_scalar: 1
  max_rollouts: 20000
  search_games: 700


anet:
  lr: 0.00025
  optimizer: "adam"
  loss: "categorical_crossentropy"
  model_file: "anets/local/hex/5x5_small_dense/temp.h5"
  activation: "selu"
  cnn_filters: # depth, filter_size, dropout (on layer output!!), padding
    - [160, 3, 0.0, "valid"]
    - [160, 3, 0.0, "same"]
    - [160, 3, 0.0, "same"]
    - [160, 3, 0.0, "same"]
    - [160, 3, 0.0, "same"]
    - [4, 1, 0.1, "same"]
  dense_layers: # depth, dropout
    - [64, 0.01]
  #  - [512, 0.2]
  #  - [256, 0.2]
  batch_size: 32
  allow_cuda: False