---
display:
  display_rate: 0.55 # in seconds

#SimWorld args:
sim_world:
  world: "hex"
  size: 6

actor:
  episodes: 100
  num_checkpoints: 6
  train_ex_size: 8
  competition_games: 0
  file_structure: "anets/local/hex/6x6conv1/"
  epsilon: 0.80
  epsilon_decay: 0.85
  epsilon_min: 0.1
  display_games: [0, 200]

mcts:
  search_duration: 3.0
  bias: 0.25
  c: 0.2
  min_h_confidence: 3
  max_h_confidence: 15
  amaf_conf_scalar: 1
  max_rollouts: 10000
  search_games: 300


anet:
  lr: 0.001
  optimizer: "adam"
  loss: "categorical_crossentropy"
  #model_file: "anets/local/hex/6x6conv1/temp.h5"
  activation: "selu"
  cnn_filters: # depth, filter_size, dropout (on layer output!!), padding
    - [148, 3, 0.0, "valid"]
    - [148, 3, 0.0, "same"]
    - [148, 3, 0.0, "same"]
    - [148, 3, 0.0, "same"]
    - [148, 3, 0.0, "same"]
    - [32, 1, 0.0, "same"]
  dense_layers: # depth, dropout
    - [96, 0.0]
  #  - [512, 0.2]
  #  - [256, 0.2]
  batch_size: 64
  allow_cuda: False