---
display:
  display_rate: 0.55 # in seconds

#SimWorld args:
sim_world:
  world: "hex_board"
  size: 4

mcts:
  episodes: 100
  search_duration: 2
  bias: 1

anet:
  lr: 0.1
  optimizer: "SGD"
  hidden_layers:
    - [50, "relu"]
    - [50, "tanh"]
    - [50, "sigmoid"]

topp:
  cache_m: 5
  games_g: 20