---
display:
  display_rate: 0.55 # in seconds

#SimWorld args:
sim_world:
  world: "hex"
  size: 6

actor:
  episodes: 10
  num_checkpoints: 0
  train_games: 1
  competition_games: 300
  anet_dir: "anets/local/hex/6x6/fit_d/"
  save_data: True
  data_dir: "data/newrand_2000g_eps215/"
  win_margin: 3
  epsilon: 0.0
  epsilon_decay: 0.97
  epsilon_min: 0.166
  display_games: []


mcts:
  search_duration: 0.3
  bias: 0.0542
  c: 0.0885
  h_confidence: 4
  max_rollouts: 40000
  search_games: 1

anet:
  lr: 0.00016
  optimizer: "adam"
  loss: "kl_divergence"
  model_file: "anets/local/hex/6x6/fit_d/best.h5"
  activation: "selu"
  cnn_filters: # depth, filter_size, dropout (on layer output!!), padding
    - [148, 3, 0.0, "valid"]
    - [148, 3, 0.0, "same"]
    - [148, 3, 0.0, "same"]
    - [148, 3, 0.0, "same"]
    - [148, 3, 0.05, "same"]
    - [32, 1, 0.01, "same"]
  dense_layers: # depth, dropout
    - [96, 0.0]
  #  - [512, 0.2]
  #  - [256, 0.2]
  batch_size: 64
  allow_cuda: False
