---
display:
  display_rate: 0.55 # in seconds

#SimWorld args:
sim_world:
  world: "hex"
  size: 4

actor:
   episodes: 40
   cache_m: 5
   epsilon: 0.8
   epsilon_decay: 0.985
   epsilon_min: 0.1

mcts:
  search_duration: 2.5
  bias: 0.2
  c: 1.5


anet:
  lr: 0.001
  optimizer: "adam"
  loss: "categorical_crossentropy"
  file_structure: "anet/hex/"
  output_activation: "softmax"
  hidden_layers:
    - [30, "tanh"]
    - [30, "tanh"]
