---
display:
  display_rate: 0.55 # in seconds

#SimWorld args:
sim_world:
  world: "hex"
  size: 6

actor:
  episodes: 20
  num_checkpoints: 21
  train_games: 70
  competition_games: 0
  anet_dir: "anets/local/hex/6x6/"
  save_data: True
  data_dir: "data/eps_022/"
  win_margin: 5
  epsilon: 0.0
  epsilon_decay: 0.97
  epsilon_min: 0.22
  display_games: []


mcts:
  search_duration: 40.0
  bias: 0.0542
  c: 0.08875
  h_confidence: 4
  max_rollouts: 40000
  search_games: 1


anet:
  lr: 0.00005
  optimizer: "adam"
  loss: "kl_divergence"
  model_file: "anets/best/hex/6x6/kld3.h5"
  activation: "selu"
  cnn_filters: # depth, filter_size, dropout (on layer output!!), padding
    - [148, 3, 0.0, "valid"]
    - [148, 3, 0.0, "same"]
    - [148, 3, 0.0, "same"]
    - [148, 3, 0.0, "same"]
    - [148, 3, 0.05, "same"]
    - [12, 1, 0.01, "same"]
  dense_layers: # depth, dropout
    - [64, 0.0]
  #  - [512, 0.2]
  #  - [256, 0.2]
  batch_size: 64
  allow_cuda: False
