display_rate: 0.1

topp:
  games_g: 400
  display_games: true
  display_games_pairs:
    - [0,  1]
  directory: "anets\\local\\hex\\4x4_better\\"
  player_type: "probabilistic"

sim_world:
  world: "hex"
  size: 4