display_rate: 0.1
allow_cuda: false
topp:
  games_g: 300
  display_games: true
  display_games_pairs:
    - [0,  1]
  #directory: "anets\\local\\hex\\5x5_small_dense\\"
  directory: "anets\\best\\hex\\5x5\\"
  player_type: "probabilistic"

sim_world:
  world: "hex"
  size: 5