display_rate: 0.75
allow_cuda: false
topp:
  games_g: 300
  display_games: 2
  display_games_pairs:
    - []
  #directory: "anets\\local\\hex\\5x5_small_dense\\"
  directory: "anets\\best\\hex\\5x5\\"
  player_type: "greedy"

sim_world:
  world: "hex"
  size: 6